Traceback (most recent call last):
  File "/home/lokmane-zed/project/DzVisionAi/back-end/src/ai/train_vehicle_model.py", line 427, in <module>
    main()
  File "/home/lokmane-zed/project/DzVisionAi/back-end/src/ai/train_vehicle_model.py", line 375, in main
    image_paths, color_labels, make_labels = load_dataset(data_dir, color_mapping, make_mapping)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lokmane-zed/project/DzVisionAi/back-end/src/ai/train_vehicle_model.py", line 104, in load_dataset
    for make in os.listdir(data_dir):
                ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/lokmane-zed/project/DzVisionAi/data/vehicle_dataset'
